<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>CV Aprendices SENA</title>
    <meta name="description" content="Crea tu hoja de vida en minutos, con una foto lista para CV, formato compatible con los filtros ATS, y descárgala en PDF, Word o compártela con un enlace.">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Barlow:wght@500;600;700&family=Work+Sans:wght@400;500;600;700&family=IBM+Plex+Mono:wght@500&display=swap" rel="stylesheet">
    <!-- Favicon package generated by Favicon.im Generator -->
<link rel="icon" type="image/x-icon" href="/favicon.ico">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="192x192" href="/android-chrome-192x192.png">
<link rel="icon" type="image/png" sizes="512x512" href="/android-chrome-512x512.png">
<meta name="theme-color" content="#ffffff">
    <style>
        :root {
            --ink: #25313b;
            --ink-soft: #65727d;
            --paper: #ffffff;
            --paper-alt: #e9f5df;
            --line: #dce4e8;
            --pass: #39a900;
            --pass-light: #e9f5df;
            --pass-dark: #247000;
            --reject: #a63d3d;
            --reject-light: #f4e3e1;
        }

        * { box-sizing: border-box; }

        html { scroll-behavior: smooth; }

        body {
            margin: 0;
            background: var(--paper);
            color: var(--ink);
            font-family: 'Work Sans', sans-serif;
            font-size: 16px;
            line-height: 1.6;
            -webkit-font-smoothing: antialiased;
        }

        h1, h2, h3 {
            font-family: 'Barlow', sans-serif;
            font-weight: 600;
            line-height: 1.15;
            margin: 0;
        }

        p { margin: 0; }

        a { color: inherit; }

        .mono {
            font-family: 'IBM Plex Mono', monospace;
            font-weight: 500;
            letter-spacing: 0.01em;
        }

        .wrap {
            max-width: 1120px;
            margin: 0 auto;
            padding: 0 32px;
        }

        @media (max-width: 640px) {
            .wrap { padding: 0 20px; }
        }

        /* ---------- Header ---------- */
        header {
            border-bottom: 1px solid var(--line);
        }

        .nav {
            display: flex;
            align-items: center;
            justify-content: space-between;
            padding: 22px 0;
        }

        .brand {
            display: flex;
            align-items: center;
            gap: 10px;
            font-family: 'Barlow', sans-serif;
            font-weight: 600;
            font-size: 19px;
        }

        .brand-mark {
            width: 36px;
            height: 36px;
            flex: 0 0 36px;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .brand-mark svg {
            display: block;
            width: 32px;
            height: 32px;
            max-width: 100%;
            max-height: 100%;
        }

        .nav-links {
            display: flex;
            align-items: center;
            gap: 28px;
            font-size: 15px;
        }

        .nav-links a.btn-outline {
            border: 1px solid var(--ink);
            padding: 8px 18px;
            border-radius: 4px;
        }

        @media (max-width: 640px) {
            .nav-links span.hide-mobile { display: none; }
        }

        /* ---------- Hero ---------- */
        .hero {
            padding: 76px 0 88px;
        }

        .hero-grid {
            display: grid;
            grid-template-columns: 1.05fr 0.95fr;
            gap: 56px;
            align-items: center;
        }

        @media (max-width: 880px) {
            .hero-grid { grid-template-columns: 1fr; }
        }

        .hero h1 {
            font-size: 46px;
            letter-spacing: -0.01em;
            max-width: 15ch;
        }

        @media (max-width: 640px) {
            .hero h1 { font-size: 34px; }
        }

        .hero p.lead {
            margin-top: 22px;
            font-size: 18px;
            color: var(--ink-soft);
            max-width: 46ch;
        }

        .cta-row {
            display: flex;
            gap: 14px;
            margin-top: 34px;
            flex-wrap: wrap;
        }

        .btn-primary {
            background: var(--pass);
            color: #fff;
            border: 1px solid var(--pass);
            padding: 13px 24px;
            border-radius: 4px;
            font-weight: 500;
            font-size: 15.5px;
            text-decoration: none;
            display: inline-block;
        }

        .btn-secondary {
            border: 1px solid var(--ink);
            padding: 13px 24px;
            border-radius: 4px;
            font-weight: 500;
            font-size: 15.5px;
            text-decoration: none;
            color: var(--ink);
        }

        .hero-note {
            margin-top: 18px;
            font-size: 13.5px;
            color: var(--ink-soft);
        }

        /* ---------- Scan visual ---------- */
        .scan-card {
            background: var(--paper);
            border: 1px solid var(--line);
            border-radius: 10px;
            padding: 22px;
            position: relative;
            overflow: hidden;
        }

        .scan-card-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            font-size: 12.5px;
            color: var(--ink-soft);
            margin-bottom: 16px;
        }

        .scan-doc {
            position: relative;
            border: 1px solid var(--line);
            border-radius: 6px;
            padding: 20px 20px 22px;
            background: var(--paper);
        }

        .scan-doc-name {
            font-weight: 600;
            font-size: 16px;
        }

        .scan-doc-role {
            font-size: 13px;
            color: var(--ink-soft);
            margin-top: 3px;
        }

        .scan-lines {
            margin-top: 16px;
            display: flex;
            flex-direction: column;
            gap: 8px;
        }

        .scan-lines div {
            height: 8px;
            border-radius: 2px;
            background: var(--paper-alt);
        }

        .scanline {
            position: absolute;
            left: 0;
            right: 0;
            height: 2px;
            background: var(--pass);
            animation: sweep 3.2s ease-in-out infinite;
        }

        @keyframes sweep {
            0%   { top: 8%; opacity: 1; }
            48%  { top: 92%; opacity: 1; }
            50%  { opacity: 0; }
            50.1%{ top: 8%; }
            100% { top: 8%; opacity: 0; }
        }

        .scan-result {
            margin-top: 16px;
            display: flex;
            align-items: center;
            justify-content: space-between;
            font-size: 13px;
            padding-top: 14px;
            border-top: 1px dashed var(--line);
        }

        .scan-badge {
            background: var(--pass-light);
            color: var(--pass-dark);
            padding: 4px 10px;
            border-radius: 3px;
            font-size: 12px;
        }

        @media (prefers-reduced-motion: reduce) {
            .scanline { animation: none; opacity: 0; }
        }

        /* ---------- Section shared ---------- */
        section { padding: 84px 0; }

        .section-alt { background: var(--paper-alt); }

        .section-head {
            max-width: 56ch;
            margin-bottom: 48px;
        }

        .section-head h2 {
            font-size: 32px;
        }

        .section-head p {
            margin-top: 14px;
            font-size: 16.5px;
            color: var(--ink-soft);
        }

        /* ---------- Before / after ---------- */
        .compare {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 28px;
        }

        @media (max-width: 720px) {
            .compare { grid-template-columns: 1fr; }
        }

        .compare-card {
            border-radius: 10px;
            padding: 24px;
            border: 1px solid var(--line);
        }

        .compare-card.no {
            background: var(--reject-light);
            border-color: #e2c3c1;
        }

        .compare-card.yes {
            background: var(--pass-light);
            border-color: #bfdfc9;
        }

        .compare-label {
            display: flex;
            align-items: center;
            gap: 8px;
            font-size: 13px;
            margin-bottom: 16px;
        }

        .compare-card.no .compare-label { color: var(--reject); }
        .compare-card.yes .compare-label { color: var(--pass-dark); }

        .dot {
            width: 8px;
            height: 8px;
            border-radius: 50%;
        }

        .compare-card.no .dot { background: var(--reject); }
        .compare-card.yes .dot { background: var(--pass); }

        .compare-mock {
            background: var(--paper);
            border-radius: 6px;
            padding: 16px;
            font-size: 13px;
        }

        .compare-mock ul {
            margin: 10px 0 0;
            padding-left: 18px;
        }

        .compare-mock .col2 {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 10px;
            margin-top: 10px;
        }

        .compare-mock .block {
            height: 9px;
            background: var(--paper-alt);
            border-radius: 2px;
            margin-top: 8px;
        }

        .compare-note {
            margin-top: 16px;
            font-size: 14px;
        }

        .compare-card.no .compare-note { color: #7a2f2f; }
        .compare-card.yes .compare-note { color: var(--pass-dark); }

        /* ---------- Steps ---------- */
        .steps {
            display: grid;
            grid-template-columns: repeat(5, 1fr);
            gap: 0;
            border-top: 1px solid var(--line);
        }

        @media (max-width: 940px) {
            .steps { grid-template-columns: repeat(2, 1fr); }
        }

        @media (max-width: 560px) {
            .steps { grid-template-columns: 1fr; }
        }

        .step {
            padding: 26px 22px 26px 0;
            border-right: 1px solid var(--line);
        }

        .steps > .step:last-child { border-right: none; }

        @media (max-width: 940px) {
            .step:nth-child(2n) { border-right: none; }
            .step { border-bottom: 1px solid var(--line); padding-right: 22px; }
        }

        .step-num {
            font-family: 'IBM Plex Mono', monospace;
            font-size: 13px;
            color: var(--pass-dark);
        }

        .step h3 {
            font-size: 16.5px;
            margin-top: 10px;
        }

        .step p {
            margin-top: 8px;
            font-size: 14px;
            color: var(--ink-soft);
        }

        /* ---------- Features ---------- */
        .features {
            display: grid;
            grid-template-columns: 1.3fr 1fr;
            gap: 24px;
        }

        @media (max-width: 820px) {
            .features { grid-template-columns: 1fr; }
        }

        .feature-main {
            border: 1px solid var(--line);
            border-radius: 10px;
            padding: 32px;
            display: flex;
            flex-direction: column;
            justify-content: space-between;
            min-height: 260px;
        }

        .feature-stack {
            display: flex;
            flex-direction: column;
            gap: 24px;
        }

        .feature-small {
            border: 1px solid var(--line);
            border-radius: 10px;
            padding: 24px;
        }

        .feature-eyebrow {
            font-size: 13px;
            color: var(--pass-dark);
        }

        .feature-main h3, .feature-small h3 {
            font-size: 21px;
            margin-top: 10px;
        }

        .feature-main p, .feature-small p {
            margin-top: 10px;
            font-size: 14.5px;
            color: var(--ink-soft);
            max-width: 42ch;
        }

        .mini-photo-frame {
            margin-top: 20px;
            display: flex;
            gap: 10px;
            align-items: center;
        }

        .mini-photo {
            width: 46px;
            height: 58px;
            border-radius: 4px;
            border: 1px solid var(--line);
        }

        .mini-photo.before { background: repeating-linear-gradient(45deg, #eceae1, #eceae1 4px, #e2ded0 4px, #e2ded0 8px); }
        .mini-photo.after { background: var(--paper-alt); }

        /* ---------- Gallery ---------- */
        .gallery-section { background: var(--paper); }

        .gallery-grid {
            display: grid;
            grid-template-columns: 1.15fr 0.85fr 0.85fr;
            grid-template-rows: 220px 170px;
            gap: 14px;
        }

        .gallery-item {
            position: relative;
            min-width: 0;
            overflow: hidden;
            border-radius: 8px;
            background: var(--paper-alt);
        }

        .gallery-item:first-child { grid-row: 1 / 3; }

        .gallery-item img {
            display: block;
            width: 100%;
            height: 100%;
            object-fit: cover;
            object-position: center;
            transition: transform 500ms ease;
        }

        .gallery-item:hover img { transform: scale(1.04); }

        .gallery-caption {
            position: absolute;
            right: 14px;
            bottom: 14px;
            left: 14px;
            padding: 12px 14px;
            color: #fff;
            background: linear-gradient(180deg, transparent, rgba(0, 50, 77, 0.88));
            font-size: 14px;
            font-weight: 600;
        }

        .gallery-caption span {
            display: block;
            margin-top: 2px;
            color: #d8efc6;
            font-family: 'IBM Plex Mono', monospace;
            font-size: 10px;
            font-weight: 500;
            text-transform: uppercase;
            letter-spacing: 0.04em;
        }

        .gallery-credit {
            margin-top: 14px;
            color: var(--ink-soft);
            font-size: 12px;
        }

        @media (max-width: 760px) {
            .gallery-grid {
                grid-template-columns: 1fr 1fr;
                grid-template-rows: 230px 170px;
            }

            .gallery-item:first-child { grid-row: auto; grid-column: 1 / 3; }
        }

        @media (max-width: 480px) {
            .gallery-grid { grid-template-rows: repeat(4, 210px); grid-template-columns: 1fr; }
            .gallery-item:first-child { grid-column: auto; }
        }

        @media (prefers-reduced-motion: reduce) {
            .gallery-item img { transition: none; }
        }

        /* ---------- CTA band ---------- */
        .cta-band {
            background: var(--ink);
            color: #fdfcf8;
            padding: 72px 0;
        }

        .cta-band h2 {
            color: #fdfcf8;
            font-size: 32px;
            max-width: 20ch;
        }

        .cta-band p {
            margin-top: 14px;
            color: #b9c2cc;
            font-size: 16px;
            max-width: 46ch;
        }

        .cta-band .cta-row { margin-top: 30px; }

        .cta-band .btn-secondary {
            border-color: #4a5766;
            color: #fdfcf8;
        }

        /* ---------- Footer ---------- */
        footer {
            padding: 32px 0;
            border-top: 1px solid var(--line);
            display: flex;
            justify-content: space-between;
            align-items: center;
            font-size: 13.5px;
            color: var(--ink-soft);
            flex-wrap: wrap;
            gap: 10px;
        }
    </style>
</head>
<body>

    <header>
        <div class="wrap nav">
            <div class="brand">
                <span class="brand-mark"><x-application-logo /></span>
                {{ config('app.name', 'HojaDeVida ATS') }}
            </div>
            <div class="nav-links">
                @auth
                    <a href="{{ route('cv.preview') }}" class="btn-outline">Ver mi CV</a>
                @else
                    <span class="hide-mobile"><a href="{{ route('login') }}">Iniciar sesión</a></span>
                    <a href="{{ route('register') }}" class="btn-outline">Crear mi CV</a>
                @endauth
            </div>
        </div>
    </header>

    <section class="hero">
        <div class="wrap hero-grid">
            <div>
                <h1>Una hoja de vida que un sistema ATS sí puede leer</h1>
                <p class="lead">
                    Completa tus datos, sube una foto y te ayudamos a dejarla lista para
                    CV, y descarga un CV en un formato simple que los filtros automáticos
                    de las empresas procesan sin problema. Sin plantillas con columnas
                    raras que terminan descartadas antes de que alguien las lea.
                </p>
                <div class="cta-row">
                    @auth
                        <a href="{{ route('cv.wizard') }}" class="btn-primary">Continuar mi CV</a>
                    @else
                        <a href="{{ route('register') }}" class="btn-primary">Crear mi CV gratis</a>
                        <a href="#como-funciona" class="btn-secondary">Ver cómo funciona</a>
                    @endauth
                </div>
                <p class="hero-note">Listo en unos 10 minutos. Exporta en PDF, Word, o compártelo con un enlace.</p>
            </div>

            <div class="scan-card" aria-hidden="true">
                <div class="scan-card-header">
                    <span>vista_previa.pdf</span>
                    <span class="mono">escaneo_ats</span>
                </div>
                <div class="scan-doc">
                    <div class="scanline"></div>
                    <p class="scan-doc-name">Laura Martínez</p>
                    <p class="scan-doc-role">Auxiliar administrativa</p>
                    <div class="scan-lines">
                        <div style="width: 92%"></div>
                        <div style="width: 78%"></div>
                        <div style="width: 85%"></div>
                        <div style="width: 65%"></div>
                    </div>
                    <div class="scan-result">
                        <span class="mono" style="color: var(--ink-soft);">coincidencia de palabras clave</span>
                        <span class="scan-badge mono">94%</span>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="section-alt">
        <div class="wrap">
            <div class="section-head">
                <h2>La mayoría de hojas de vida ni siquiera llegan a un reclutador</h2>
                <p>
                    Antes de que una persona la vea, un software la escanea. Si el diseño
                    usa columnas, tablas o texto dentro de imágenes, el sistema puede leer
                    los datos en el orden equivocado, o simplemente no leerlos.
                </p>
            </div>

            <div class="compare">
                <div class="compare-card no">
                    <div class="compare-label"><span class="dot"></span> Diseño con columnas e iconos</div>
                    <div class="compare-mock">
                        <div class="col2">
                            <div>
                                <div class="block" style="width: 70%;"></div>
                                <div class="block" style="width: 55%;"></div>
                                <div class="block" style="width: 60%;"></div>
                            </div>
                            <div>
                                <div class="block" style="width: 80%;"></div>
                                <div class="block" style="width: 45%;"></div>
                                <div class="block" style="width: 65%;"></div>
                            </div>
                        </div>
                    </div>
                    <p class="compare-note">El parser puede mezclar el orden de las dos columnas y perder el hilo entre cargo y empresa.</p>
                </div>

                <div class="compare-card yes">
                    <div class="compare-label"><span class="dot"></span> Una sola columna, texto plano</div>
                    <div class="compare-mock">
                        <div class="block" style="width: 90%;"></div>
                        <div class="block" style="width: 70%;"></div>
                        <div class="block" style="width: 82%;"></div>
                        <div class="block" style="width: 60%;"></div>
                    </div>
                    <p class="compare-note">El sistema lee cargo, empresa y fechas en el orden correcto, de arriba hacia abajo.</p>
                </div>
            </div>
        </div>
    </section>

    <section id="como-funciona">
        <div class="wrap">
            <div class="section-head">
                <h2>Cómo funciona</h2>
                <p>Cinco pasos, en un solo formulario. Guardamos tu progreso en cada uno.</p>
            </div>

            <div class="steps">
                <div class="step">
                    <span class="step-num mono">01</span>
                    <h3>Tus datos</h3>
                    <p>Contacto, estudios y experiencia laboral, con logros medibles.</p>
                </div>
                <div class="step">
                    <span class="step-num mono">02</span>
                    <h3>Tu foto</h3>
                    <p>Súbela y la recortamos automáticamente al formato de una foto de CV.</p>
                </div>
                <div class="step">
                    <span class="step-num mono">03</span>
                    <h3>Perfil profesional</h3>
                    <p>Un resumen breve, habilidades e idiomas, en tu propio lenguaje.</p>
                </div>
                <div class="step">
                    <span class="step-num mono">04</span>
                    <h3>Revisa el resultado</h3>
                    <p>Vista previa con una plantilla pensada para pasar los filtros ATS.</p>
                </div>
                <div class="step">
                    <span class="step-num mono">05</span>
                    <h3>Descarga o comparte</h3>
                    <p>PDF, Word, o un enlace público para enviar directamente.</p>
                </div>
            </div>
        </div>
    </section>

    <section class="section-alt">
        <div class="wrap">
            <div class="section-head">
                <h2>Todo lo que necesitas para postularte hoy</h2>
            </div>

            <div class="features">
                <div class="feature-main">
                    <div>
                        <span class="feature-eyebrow mono">foto de perfil</span>
                        <h3>Una foto lista para CV, sin salir de la página</h3>
                        <p>Subes cualquier foto y la ajustamos al tamaño y encuadre estándar de una foto de hoja de vida, con brillo y nitidez mejorados automáticamente.</p>
                    </div>
                    <div class="mini-photo-frame">
                        <div class="mini-photo before"></div>
                        <span class="mono" style="color: var(--ink-soft); font-size: 13px;">→</span>
                        <div class="mini-photo after"></div>
                    </div>
                </div>

                <div class="feature-stack">
                    <div class="feature-small">
                        <span class="feature-eyebrow mono">exportar</span>
                        <h3>PDF y Word</h3>
                        <p>El mismo contenido, en el formato que te pida cada empresa.</p>
                    </div>
                    <div class="feature-small">
                        <span class="feature-eyebrow mono">compartir</span>
                        <h3>Enlace público</h3>
                        <p>Actívalo cuando quieras compartir tu CV sin adjuntar un archivo.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="gallery-section">
        <div class="wrap">
            <div class="section-head">
                <h2>Personas reales, caminos distintos</h2>
                <p>Una hoja de vida también cuenta lo que estás construyendo: tu oficio, tu práctica y el siguiente paso profesional.</p>
            </div>

            <div class="gallery-grid">
                <figure class="gallery-item">
                    <img src="https://www.tropicanafm.com/wp-content/uploads/2025/06/18062025-Reforma-Laboral-SENA-1024x576.png" alt="Aprendices en formación colaborando en un aula" loading="lazy">
                    <figcaption class="gallery-caption">Aprender haciendo<span>formación técnica</span></figcaption>
                </figure>
                <figure class="gallery-item">
                    <img src="https://www.elnuevosiglo.com.co/sites/default/files/2025-05/FOTO%2011-17824.jpg" alt="Grupo de estudiantes trabajando en equipo" loading="lazy">
                    <figcaption class="gallery-caption">Trabajo en equipo<span>habilidades que cuentan</span></figcaption>
                </figure>
                <figure class="gallery-item">
                    <img src="https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&amp;fit=crop&amp;w=800&amp;q=85" alt="Personas en una reunión de trabajo" loading="lazy">
                    <figcaption class="gallery-caption">Listos para aportar<span>primer empleo</span></figcaption>
                </figure>
                <figure class="gallery-item">
                    <img src="https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&amp;fit=crop&amp;w=800&amp;q=85" alt="Joven profesional en un entorno de aprendizaje" loading="lazy">
                    <figcaption class="gallery-caption">Cada logro suma<span>perfil profesional</span></figcaption>
                </figure>
            </div>

            <p class="gallery-credit">Imágenes de referencia: Unsplash. La galería puede reemplazarse por fotografías propias de aprendices SENA.</p>
        </div>
    </section>

    <div class="cta-band">
        <div class="wrap">
            <h2>Tu próxima entrevista empieza por un CV que se pueda leer</h2>
            <p>Crea tu cuenta y ten tu hoja de vida lista hoy mismo.</p>
            <div class="cta-row">
                @auth
                    <a href="{{ route('cv.wizard') }}" class="btn-primary">Continuar mi CV</a>
                @else
                    <a href="{{ route('register') }}" class="btn-primary">Crear mi CV gratis</a>
                    <a href="{{ route('login') }}" class="btn-secondary">Ya tengo cuenta</a>
                @endauth
            </div>
        </div>
    </div>

    <footer>
        <div class="wrap" style="display: flex; justify-content: space-between; align-items: center; flex-wrap: wrap; gap: 10px;">
            <span>{{ config('app.name', 'HojaDeVida ATS') }} — hecho para aprendices que están buscando su próximo empleo.</span>
            <span>&copy; {{ date('Y') }}</span>
        </div>
    </footer>

</body>
</html>
